import Foundation
import XCTest

@testable import BeautyOnTAppPro

final class ThemeSyncServiceTests: XCTestCase {
  // A minimal but structurally real templates/index.json: greeting, a
  // two-slide hero, and a product rail — the smallest document that passes
  // home validation.
  private static let homeJSON = """
    {
      "sections": {
        "greeting": {
          "type": "bot-greeting",
          "settings": {
            "kicker": "BEAUTYONTAPP 🖤",
            "greeting_prefix": "Happy",
            "greeting_suffix": "Bestie 🖤",
            "subtext": "Your beauty, on tap."
          }
        },
        "hero": {
          "type": "custom-collection-slider",
          "blocks": {
            "slide-one": {
              "type": "slide",
              "settings": {
                "image": "shopify://shop_images/hero-august.jpg",
                "slide-heading": "New week, new heroes",
                "description": "Fresh drops",
                "btn-text": "Shop now",
                "btn-link": "shopify://collections/new-arrivals"
              }
            },
            "slide-two": {
              "type": "slide",
              "settings": {
                "image": "shopify://shop_images/hero-glow.jpg",
                "slide-heading": "Glow edit",
                "description": "Radiance picks",
                "btn-text": "Shop glow",
                "btn-link": "/collections/glow"
              }
            }
          },
          "block_order": ["slide-one", "slide-two"]
        },
        "rail": {
          "type": "featured-collection",
          "settings": {
            "heading": "Korean Skincare",
            "collection": "korean-skincare",
            "products_count": 12
          }
        }
      },
      "order": ["greeting", "hero", "rail"]
    }
    """

  private func makeService(
    responses: @escaping @Sendable (URLRequest) async throws -> (
      Data, URLResponse
    )
  ) -> (service: ThemeSyncService, directory: URL) {
    let directory = FileManager.default.temporaryDirectory
      .appendingPathComponent("theme-sync-tests-\(UUID().uuidString)")
    let service = ThemeSyncService(
      networkLoader: responses,
      directory: directory
    )
    return (service, directory)
  }

  private static func httpResponse(
    for request: URLRequest,
    status: Int = 200
  ) -> HTTPURLResponse {
    HTTPURLResponse(
      url: request.url!,
      statusCode: status,
      httpVersion: nil,
      headerFields: nil
    )!
  }

  private static func metaobjectEnvelope(embedding json: String) throws -> Data {
    try JSONSerialization.data(
      withJSONObject: [
        "data": [
          "metaobject": [
            "updatedAt": "2026-08-12T04:00:00Z",
            "indexJSON": ["value": json],
          ]
        ]
      ]
    )
  }

  // MARK: Parsing and validation

  func testParsesRemoteHomeDocument() throws {
    let snapshot = try ThemeHomeSnapshot.parse(
      data: Data(Self.homeJSON.utf8)
    )

    XCTAssertEqual(snapshot.sections.count, 3)
    XCTAssertTrue(snapshot.isAcceptableHome)

    guard case .hero(_, let slides) = snapshot.sections[1] else {
      return XCTFail("Expected hero at storefront position 2")
    }
    XCTAssertEqual(slides.count, 2)
    XCTAssertEqual(
      slides.first?.imageReference,
      "shopify://shop_images/hero-august.jpg"
    )
    XCTAssertEqual(
      ShopifyAsset.url(from: slides.first?.imageReference)?.absoluteString,
      "https://beautyontapp.com/cdn/shop/files/hero-august.jpg"
    )
    XCTAssertEqual(slides.first?.link, .collection("new-arrivals"))
  }

  func testRejectsDocumentsThatCannotCarryHome() throws {
    let noHero = """
      {
        "sections": {
          "one": {"type": "bot-greeting", "settings": {}},
          "two": {"type": "featured-collection",
                  "settings": {"collection": "skincare"}},
          "three": {"type": "bot-greeting", "settings": {}}
        },
        "order": ["one", "two", "three"]
      }
      """
    XCTAssertFalse(
      try ThemeHomeSnapshot.parse(data: Data(noHero.utf8)).isAcceptableHome
    )

    let tooSparse = """
      {
        "sections": {
          "one": {"type": "bot-greeting", "settings": {}}
        },
        "order": ["one"]
      }
      """
    XCTAssertFalse(
      try ThemeHomeSnapshot.parse(data: Data(tooSparse.utf8))
        .isAcceptableHome
    )

    XCTAssertThrowsError(
      try ThemeHomeSnapshot.parse(data: Data("not json".utf8))
    )
  }

  func testStripsShopifyAutoGeneratedBanner() throws {
    // Shopify saves templates/index.json with a leading comment banner;
    // the live document is not valid strict JSON until it is stripped.
    let bannered = """
      /*
       * ------------------------------------------------------------
       * IMPORTANT: The contents of this file are auto-generated.
       * ------------------------------------------------------------
       */
      \(Self.homeJSON)
      """
    let snapshot = try ThemeHomeSnapshot.parse(data: Data(bannered.utf8))
    XCTAssertTrue(snapshot.isAcceptableHome)

    // Banner or no banner, the normalised payload hash is identical, so a
    // transport switch can never masquerade as a content change.
    let stripped = ThemeSnapshotLoader.strippingThemeBanner(
      from: Data(bannered.utf8)
    )
    XCTAssertEqual(
      ThemeSyncPayload.hash(of: stripped),
      ThemeSyncPayload.hash(
        of: Data(Self.homeJSON.trimmingCharacters(
          in: .whitespacesAndNewlines
        ).utf8)
      )
    )
  }

  func testBanneredRemoteDocumentSyncsAndNormalises() async throws {
    let bannered = "/* auto-generated */\n\(Self.homeJSON)"
    let envelope = try Self.metaobjectEnvelope(embedding: bannered)
    let (service, directory) = makeService { request in
      (envelope, Self.httpResponse(for: request))
    }
    defer { try? FileManager.default.removeItem(at: directory) }

    let payload = await service.refresh(force: true)

    XCTAssertEqual(payload?.transport, .metaobject)
    XCTAssertEqual(
      payload.map { String(decoding: $0.rawJSON, as: UTF8.self).prefix(1) },
      "{"
    )
  }

  // MARK: Transports

  func testMetaobjectTransportDeliversAndPersists() async throws {
    let envelope = try Self.metaobjectEnvelope(embedding: Self.homeJSON)
    let (service, directory) = makeService { request in
      (envelope, Self.httpResponse(for: request))
    }
    defer { try? FileManager.default.removeItem(at: directory) }

    let payload = await service.refresh(force: true)

    XCTAssertEqual(payload?.transport, .metaobject)
    XCTAssertEqual(payload?.rawJSON, Data(Self.homeJSON.utf8))

    let stored = await service.storedPayload()
    XCTAssertEqual(stored?.hash, payload?.hash)
    XCTAssertEqual(stored?.transport, .metaobject)
  }

  func testFallsBackToFilesCDNWhenMetaobjectIsAbsent() async throws {
    let (service, directory) = makeService { request in
      if request.httpMethod == "POST" {
        // Storefront responds, but no metaobject exists yet.
        return (
          Data(#"{"data": {"metaobject": null}}"#.utf8),
          Self.httpResponse(for: request)
        )
      }
      return (Data(Self.homeJSON.utf8), Self.httpResponse(for: request))
    }
    defer { try? FileManager.default.removeItem(at: directory) }

    let payload = await service.refresh(force: true)

    XCTAssertEqual(payload?.transport, .filesCDN)
    XCTAssertEqual(payload?.rawJSON, Data(Self.homeJSON.utf8))
  }

  func testInvalidRemoteDocumentsAreNeverAccepted() async throws {
    // Both transports answer with 200s whose bodies must be rejected: the
    // metaobject carries a truncated document, the CDN an error page.
    let truncated = try Self.metaobjectEnvelope(
      embedding: #"{"sections": {}, "order": []}"#
    )
    let (service, directory) = makeService { request in
      if request.httpMethod == "POST" {
        return (truncated, Self.httpResponse(for: request))
      }
      return (
        Data("<html>Not found</html>".utf8),
        Self.httpResponse(for: request)
      )
    }
    defer { try? FileManager.default.removeItem(at: directory) }

    let payload = await service.refresh(force: true)

    XCTAssertNil(payload)
    let stored = await service.storedPayload()
    XCTAssertNil(stored)
  }

  func testHTTPErrorsFallThroughWithoutPoisoningStorage() async throws {
    let envelope = try Self.metaobjectEnvelope(embedding: Self.homeJSON)
    // First pass: everything healthy. Second pass: the storefront serves
    // errors — the previously stored payload must survive untouched.
    let isHealthy = SendableBox(true)
    let (service, directory) = makeService { request in
      if isHealthy.value {
        return (envelope, Self.httpResponse(for: request))
      }
      return (
        Data("Service Unavailable".utf8),
        Self.httpResponse(for: request, status: 503)
      )
    }
    defer { try? FileManager.default.removeItem(at: directory) }

    let first = await service.refresh(force: true)
    XCTAssertNotNil(first)

    isHealthy.value = false
    let second = await service.refresh(force: true)
    XCTAssertNil(second)

    let stored = await service.storedPayload()
    XCTAssertEqual(stored?.hash, first?.hash)
  }

  func testRefreshIsThrottledBetweenForegrounds() async throws {
    let envelope = try Self.metaobjectEnvelope(embedding: Self.homeJSON)
    let requestCount = SendableBox(0)
    let (service, directory) = makeService { request in
      requestCount.value += 1
      return (envelope, Self.httpResponse(for: request))
    }
    defer { try? FileManager.default.removeItem(at: directory) }

    let first = await service.refresh()
    XCTAssertNotNil(first)
    let throttled = await service.refresh()
    XCTAssertNil(throttled)
    XCTAssertEqual(requestCount.value, 1)

    let forced = await service.refresh(force: true)
    XCTAssertNotNil(forced)
    XCTAssertEqual(requestCount.value, 2)
  }

  // MARK: Stored payload integrity

  func testTamperedDiskPayloadIsDiscarded() async throws {
    let envelope = try Self.metaobjectEnvelope(embedding: Self.homeJSON)
    let (service, directory) = makeService { request in
      (envelope, Self.httpResponse(for: request))
    }
    defer { try? FileManager.default.removeItem(at: directory) }

    _ = await service.refresh(force: true)
    let payloadURL = directory.appendingPathComponent("home.json")
    try Data("tampered".utf8).write(to: payloadURL)

    let stored = await service.storedPayload()
    XCTAssertNil(stored)
  }

  func testPayloadHashIsStableForIdenticalBytes() {
    let first = ThemeSyncPayload(
      rawJSON: Data(Self.homeJSON.utf8),
      transport: .metaobject
    )
    let second = ThemeSyncPayload(
      rawJSON: Data(Self.homeJSON.utf8),
      transport: .filesCDN
    )
    XCTAssertEqual(first.hash, second.hash)
    XCTAssertNotEqual(
      first.hash,
      ThemeSyncPayload.hash(of: Data("other".utf8))
    )
  }

  // MARK: Prefetch geometry

  @MainActor
  func testPrefetchMirrorsHomeViewRequestGeometry() throws {
    let snapshot = try ThemeHomeSnapshot.parse(
      data: Data(Self.homeJSON.utf8)
    )
    let requests = ThemeSnapshotStore.prefetchRequests(for: snapshot)

    XCTAssertEqual(requests.count, 2)
    // Hero slides prefetch at the exact width HomeView renders them, so the
    // pipeline cache key matches and the view never re-downloads.
    XCTAssertTrue(
      requests.allSatisfy {
        $0.url.query?.contains("width=900") == true
      }
    )
  }
}

/// Tiny reference box so stubbed loaders can mutate state across the
/// @Sendable closure boundary in tests.
private final class SendableBox<Value>: @unchecked Sendable {
  private let lock = NSLock()
  private var storage: Value

  init(_ value: Value) {
    storage = value
  }

  var value: Value {
    get {
      lock.lock()
      defer { lock.unlock() }
      return storage
    }
    set {
      lock.lock()
      defer { lock.unlock() }
      storage = newValue
    }
  }
}
